const neutralCards = [
    { id: "10301310", name: "至高の凌駕", cost: 4, rarity: "ブロンズ", group: "new-n" },
    { id: "10301110", name: "干絶の使徒", cost: 4, rarity: "ブロンズ", group: "new-n" },
    { id: "10302110", name: "嘆きに立ちし者", cost: 2, rarity: "シルバー", group: "new-n" },
    { id: "10304120", name: "干絶の顕現ギルネリーゼ", cost: 3, rarity: "レジェンド", group: "new-n" },
    { id: "10303110", name: "勇気に満ちし者", cost: 3, rarity: "ゴールド", group: "new-n" },
    { id: "10303210", name: "試練の石板", cost: 3, rarity: "ゴールド", group: "new-n" },
    { id: "10304110", name: "絶大の顕現マゼルベイン", cost: 4, rarity: "レジェンド", group: "new-n" },

    { id: "10001210", name: "探偵のルーペ", cost: 3, rarity: "ブロンズ", group: "normal-n" },
    { id: "10001110", name: "不屈のファイター", cost: 2, rarity: "ブロンズ", group: "normal-n" },
    { id: "10001120", name: "ベルエンジェルリア", cost: 2, rarity: "ブロンズ", group: "normal-n" },
    { id: "10001130", name: "激震のゴリアテ", cost: 4, rarity: "ブロンズ", group: "normal-n" },
    { id: "10101110", name: "グリードケルブルビィ", cost: 2, rarity: "ブロンズ", group: "normal-n" },
    { id: "10101120", name: "観察の探偵", cost: 3, rarity: "ブロンズ", group: "normal-n" },
    { id: "10101310", name: "ゴブリンの襲撃", cost: 5, rarity: "ブロンズ", group: "normal-n" },
    { id: "10201310", name: "リバースチェンジ", cost: 2, rarity: "ブロンズ", group: "normal-n" },
    { id: "10201110", name: "二刀のゴブリン", cost: 1, rarity: "ブロンズ", group: "normal-n" },
    { id: "10002110", name: "煌響の使者アンリエット", cost: 3, rarity: "シルバー", group: "normal-n" },
    { id: "10002210", name: "冒険者のギルド", cost: 3, rarity: "シルバー", group: "normal-n" },
    { id: "10002120", name: "キャラバンマンモス", cost: 7, rarity: "シルバー", group: "normal-n" },
    { id: "10102310", name: "熾天使の福音", cost: 3, rarity: "シルバー", group: "normal-n" },
    { id: "10102110", name: "迸る光明アポロン", cost: 3, rarity: "シルバー", group: "normal-n" },
    { id: "10202110", name: "メイドエンジェルチェレッタ", cost: 2, rarity: "シルバー", group: "normal-n" },
    { id: "10103110", name: "楽朗の天宮フィルドア", cost: 2, rarity: "ゴールド", group: "normal-n" },
    { id: "10103310", name: "神の雷霆", cost: 4, rarity: "ゴールド", group: "normal-n" },
    { id: "10203110", name: "絆の天使レイナ", cost: 7, rarity: "ゴールド", group: "normal-n" },
    { id: "10203120", name: "雷火の双神フニカル＆ヤヴンハール", cost: 2, rarity: "ゴールド", group: "normal-n" },
    { id: "10104110", name: "勇壮の堕天使オリヴィエ", cost: 7, rarity: "レジェンド", group: "normal-n" },
    { id: "10104120", name: "最果ての罪サタン", cost: 10, rarity: "レジェンド", group: "normal-n" },
    { id: "10204120", name: "颶風の天業グリームニル", cost: 3, rarity: "レジェンド", group: "normal-n" },
    { id: "10204110", name: "運命の黄昏オーディン", cost: 7, rarity: "レジェンド", group: "normal-n" },
];

const cardData = {
    "エルフ": {
        classCards: [
            { id: "10312120", name: "樹海の戦士", cost: 4, rarity: "シルバー", group: "new" },
            { id: "10311120", name: "妖精剣の担い手", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10311310", name: "野生の猛襲", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10311110", name: "不殺の肯定者", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10313310", name: "駆逐の死矢", cost: 1, rarity: "ゴールド", group: "new" },
            { id: "10312110", name: "不殺の祈祷者", cost: 6, rarity: "シルバー", group: "new" },
            { id: "10312210", name: "不殺の里", cost: 3, rarity: "シルバー", group: "new" },
            { id: "10313110", name: "不殺の団結者", cost: 9, rarity: "ゴールド", group: "new" },
            { id: "10314120", name: "絶命の顕現エズディア", cost: 8, rarity: "レジェンド", group: "new" },
            { id: "10314110", name: "不殺の継承者クルル", cost: 4, rarity: "レジェンド", group: "new" },
            { id: "10011120", name: "ストレイビーストマン", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10011110", name: "フェアリーテイマー", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10011210", name: "繚乱の庭", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10011130", name: "温厚なるトレント", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10111310", name: "妖精の招集", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10111110", name: "舞い踊る妖精", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10111120", name: "コンタクトフェアリー", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10111140", name: "働きバッタ", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10111150", name: "言の葉のエルダーウィードマン", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10111130", name: "深奥のフェアリービースト", cost: 8, rarity: "ブロンズ", group: "normal" },
            { id: "10211110", name: "ワイルドガール", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10211310", name: "森の行進", cost: 7, rarity: "ブロンズ", group: "normal" },
            { id: "10211120", name: "木槌のドワーフ", cost: 5, rarity: "ブロンズ", group: "normal" },

            { id: "10012110", name: "アドベンチャーエルフメイ", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10112120", name: "純粋なるウォーターフェアリー", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10012310", name: "虫の知らせ", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10112130", name: "ベビーカーバンクル", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10112210", name: "燐光の岩", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10112310", name: "薫交の思慕", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10012120", name: "ソニックアーチャーセルウィン", cost: 7, rarity: "シルバー", group: "normal" },
            { id: "10112110", name: "フロストクリスタリアエリン", cost: 7, rarity: "シルバー", group: "normal" },
            { id: "10212310", name: "樹上からの急襲", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10212110", name: "アーデントエルフレオネル", cost: 6, rarity: "シルバー", group: "normal" },
            { id: "10212120", name: "フェアリーフェンサー", cost: 2, rarity: "シルバー", group: "normal" },

            { id: "10113110", name: "ピュアクリスタリアリリィ", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10113140", name: "殺戮のリノセウス", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10113210", name: "聖樹の杖", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10113120", name: "薫交の天宮バックウッド", cost: 5, rarity: "ゴールド", group: "normal" },
            { id: "10113130", name: "煌撃の戦士ベイル", cost: 8, rarity: "ゴールド", group: "normal" },
            { id: "10213310", name: "花園の導き", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10213110", name: "フォレストシバルリーシンシア", cost: 2, rarity: "ゴールド", group: "normal" },

            { id: "10114130", name: "ビギンズブレイダーアマツ", cost: 3, rarity: "レジェンド", group: "normal" },
            { id: "10114110", name: "自然の妖精姫アリア", cost: 6, rarity: "レジェンド", group: "normal" },
            { id: "10114120", name: "豊麗なるローズクイーン", cost: 9, rarity: "レジェンド", group: "normal" },
            { id: "10214110", name: "翅の女王ティターニア", cost: 4, rarity: "レジェンド", group: "normal" },
            { id: "10214120", name: "絡み付く密林リマーガ", cost: 7, rarity: "レジェンド", group: "normal" },
        ]
    },
    "ロイヤル": {
        classCards: [
            { id: "10322110", name: "簒奪の祈祷者", cost: 2, rarity: "シルバー", group: "new" },
            { id: "10321110", name: "簒奪の肯定者", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10321310", name: "シールドバッシュ", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10321120", name: "剣聖の同胞", cost: 6, rarity: "ブロンズ", group: "new" },
            { id: "10323110", name: "簒奪の団結者", cost: 4, rarity: "ゴールド", group: "new" },
            { id: "10322120", name: "スナッピースカウト", cost: 5, rarity: "シルバー", group: "new" },
            { id: "10322210", name: "簒奪のアジト", cost: 1, rarity: "シルバー", group: "new" },
            { id: "10323310", name: "返還の剣閃", cost: 1, rarity: "ゴールド", group: "new" },
            { id: "10324120", name: "空絶の顕現オクトリス", cost: 3, rarity: "レジェンド", group: "new" },
            { id: "10324110", name: "簒奪の継承者シンセライズ", cost: 6, rarity: "レジェンド", group: "new" },

            { id: "10021110", name: "刹那のクイックブレイダー", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10021310", name: "メイドの作法", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10021120", name: "バトルマーチャント", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10021130", name: "ケンタウロスの騎士", cost: 8, rarity: "ブロンズ", group: "normal" },
            { id: "10121150", name: "異端の侍", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10121110", name: "愛の騎士イアン", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10121130", name: "救援のルミナスヒーラーリララ", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10121140", name: "ミリタリードッグ", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10121310", name: "剣士の斬撃", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10121120", name: "ピースディーラーエルネスタ", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10221310", name: "商談成立", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10221120", name: "暗闘のニンジャマスター", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10221110", name: "トリガーメイドセリエ", cost: 2, rarity: "ブロンズ", group: "normal" },

            { id: "10022110", name: "王家の御者", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10022120", name: "魔煌のトリックスターラスティ", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10022210", name: "正統なる王冠", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10122110", name: "統率のルミナスナイト", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10122140", name: "忍びのムササビ", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10122130", name: "勇猛のルミナスランサー", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10122310", name: "王断の威光", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10122120", name: "卓越のルミナスメイジ", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10222120", name: "オーディナリーナイトラキル", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10222110", name: "豪胆なる副団長ゲルト", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10222310", name: "三将姫の乱撃", cost: 2, rarity: "シルバー", group: "normal" },

            { id: "10123120", name: "サイレントスナイパーワルツ", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10123130", name: "王断の天宮スタチウム", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10123310", name: "テンタクルバイト", cost: 7, rarity: "ゴールド", group: "normal" },
            { id: "10123110", name: "レヴィオンアックスジェノ", cost: 8, rarity: "ゴールド", group: "normal" },
            { id: "10123140", name: "煌刃の勇者アマリア", cost: 8, rarity: "ゴールド", group: "normal" },
            { id: "10223110", name: "ソードプリンセスロゼ", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10223120", name: "休日の王女プリム", cost: 2, rarity: "ゴールド", group: "normal" },

            { id: "10124130", name: "常在戦場カゲミツ", cost: 3, rarity: "レジェンド", group: "normal" },
            { id: "10124110", name: "レヴィオンの迅雷アルベール", cost: 5, rarity: "レジェンド", group: "normal" },
            { id: "10124120", name: "白銀の騎士団長エミリア", cost: 6, rarity: "レジェンド", group: "normal" },
            { id: "10224120", name: "レヴィオンの超越者ユリウス", cost: 8, rarity: "レジェンド", group: "normal" },
            { id: "10224110", name: "静寂のアナテマギルダリア", cost: 6, rarity: "レジェンド", group: "normal" },
        ]
    },
    "ウィッチ": {
        classCards: [
            { id: "10332310", name: "デュアルクリエイト", cost: 4, rarity: "シルバー", group: "new" },
            { id: "10331310", name: "クリスタルゲイジング", cost: 4, rarity: "ブロンズ", group: "new" },
            { id: "10331110", name: "真実の肯定者", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10331120", name: "五行の修行者", cost: 4, rarity: "ブロンズ", group: "new" },
            { id: "10333310", name: "虚偽の術式", cost: 2, rarity: "ゴールド", group: "new" },
            { id: "10332110", name: "真実の祈祷者", cost: 5, rarity: "シルバー", group: "new" },
            { id: "10332210", name: "真実の研究施設", cost: 3, rarity: "シルバー", group: "new" },
            { id: "10333110", name: "真実の団結者", cost: 3, rarity: "ゴールド", group: "new" },
            { id: "10334120", name: "絶尽の顕現ライオ", cost: 9, rarity: "レジェンド", group: "new" },
            { id: "10334110", name: "真実の継承者ヴェハリヤー", cost: 2, rarity: "レジェンド", group: "new" },

            { id: "10031310", name: "知恵の輝き", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10031210", name: "魔女の錬金釜", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10031320", name: "真理の召喚", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10031110", name: "閃光の魔法剣士", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10131320", name: "ストームブラスト", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10131310", name: "虹の奇跡", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10131120", name: "見習い占星術師", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10131130", name: "オウルサモナー", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10131140", name: "夢想のペンギンウィザード", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10131110", name: "ルーンブレイドコンダクター", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10231120", name: "魔導の司書", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10231310", name: "アイスピアース", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10231110", name: "憧憬の魔女メルヴィ", cost: 2, rarity: "ブロンズ", group: "normal" },

            { id: "10032310", name: "イラプション", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10032110", name: "相貌の魔女レミラミ", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10032120", name: "ブレイズデストロイヤー", cost: 10, rarity: "シルバー", group: "normal" },
            { id: "10132110", name: "アドラブルティーチャーミラ", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10132310", name: "理光の証明", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10132120", name: "ワンダーウィッチエミル", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10132130", name: "マナリアの学徒ウィリアム", cost: 6, rarity: "シルバー", group: "normal" },
            { id: "10132320", name: "スノーアウェイク", cost: 8, rarity: "シルバー", group: "normal" },
            { id: "10232120", name: "調香の魔術師", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10232110", name: "否定の詠唱バーゼント", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10232310", name: "カオスフレイム", cost: 3, rarity: "シルバー", group: "normal" },

            { id: "10133120", name: "魔法の薬剤師ペネロピー", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10133310", name: "宿題やるですぅ！", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10133130", name: "理光の天宮エーデルワイス", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10133110", name: "黎明の錬金術師ノノ", cost: 5, rarity: "ゴールド", group: "normal" },
            { id: "10133320", name: "鬼呼びの術", cost: 7, rarity: "ゴールド", group: "normal" },
            { id: "10233310", name: "パメラの舞踏", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10233110", name: "マナリアの剣士オーウェン", cost: 3, rarity: "ゴールド", group: "normal" },

            { id: "10134120", name: "マナリアフレンズアン＆グレア", cost: 5, rarity: "レジェンド", group: "normal" },
            { id: "10134110", name: "五行の果てクオン", cost: 7, rarity: "レジェンド", group: "normal" },
            { id: "10134310", name: "オーバーディメンション", cost: 18, rarity: "レジェンド", group: "normal" },
            { id: "10234120", name: "アダマントアルケミストノーマン", cost: 6, rarity: "レジェンド", group: "normal" },
            { id: "10234110", name: "暴食のアナテマララアンセム", cost: 8, rarity: "レジェンド", group: "normal" },
        ]
    },
    "ドラゴン": {
        classCards: [
            { id: "10342210", name: "侮蔑の国", cost: 2, rarity: "シルバー", group: "new" },
            { id: "10341120", name: "吹雪のドラゴニュート", cost: 6, rarity: "ブロンズ", group: "new" },
            { id: "10341110", name: "侮蔑の肯定者", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10341310", name: "サンダーレイジ", cost: 3, rarity: "ブロンズ", group: "new" },
            { id: "10343110", name: "侮蔑の団結者", cost: 6, rarity: "ゴールド", group: "new" },
            { id: "10342110", name: "侮蔑の祈祷者", cost: 5, rarity: "シルバー", group: "new" },
            { id: "10342120", name: "オーシャンライダー", cost: 3, rarity: "シルバー", group: "new" },
            { id: "10343310", name: "蒼炎の猛威", cost: 1, rarity: "ゴールド", group: "new" },
            { id: "10344110", name: "侮蔑の継承者アジュラフリート", cost: 9, rarity: "レジェンド", group: "new" },
            { id: "10344120", name: "烈絶の顕現ガルミーユ", cost: 5, rarity: "レジェンド", group: "new" },

            { id: "10041310", name: "ドラゴニュートクラッシュ", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10041110", name: "烈火のファイアリザード", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10041120", name: "戦斧の竜殺し", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10041130", name: "シャークソルジャー", cost: 8, rarity: "ブロンズ", group: "normal" },
            { id: "10141140", name: "竜育の少女", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10141130", name: "駆け出しのドラゴンスレイヤー", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10141150", name: "白鱗の御使い", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10141120", name: "海溝の大剣竜", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10141310", name: "ディザスターブレス", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10141110", name: "雲海の騎竜兵", cost: 8, rarity: "ブロンズ", group: "normal" },
            { id: "10241310", name: "オルカの呼び声", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10241120", name: "飛躍のアイボリードラゴン", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10241110", name: "庇護の知竜", cost: 10, rarity: "ブロンズ", group: "normal" },

            { id: "10042310", name: "竜の啓示", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10042110", name: "猛撃のドラゴンウォーリアー", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10042120", name: "咆哮の竜使い", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10142310", name: "栄弦の奏楽", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10142120", name: "風を駆る者エイファ", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10142130", name: "風を読む者ゼル", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10142140", name: "艶麗なる竜人マリオン", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10142110", name: "煌牙の義勇キット", cost: 6, rarity: "シルバー", group: "normal" },
            { id: "10242210", name: "炎竜の剣", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10242110", name: "宿願のドラゴニュートプリンセス", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10242120", name: "歴戦のマーマン", cost: 5, rarity: "シルバー", group: "normal" },

            { id: "10143210", name: "乙姫の扇", cost: 1, rarity: "ゴールド", group: "normal" },
            { id: "10143120", name: "栄弦の天宮リュウフウ", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10143130", name: "荒波のドラグーンザハール", cost: 6, rarity: "ゴールド", group: "normal" },
            { id: "10143140", name: "ナイトフォールドラゴン", cost: 9, rarity: "ゴールド", group: "normal" },
            { id: "10143110", name: "再臨のジェネシスドラゴン", cost: 10, rarity: "ゴールド", group: "normal" },
            { id: "10243310", name: "ドラゴニックストライク", cost: 6, rarity: "ゴールド", group: "normal" },
            { id: "10243110", name: "蒼海の裁きネプチューン", cost: 7, rarity: "ゴールド", group: "normal" },

            { id: "10144120", name: "覇道の竜翼フォルテ", cost: 6, rarity: "レジェンド", group: "normal" },
            { id: "10144110", name: "灼熱のアナテマバーンドナイト", cost: 7, rarity: "レジェンド", group: "normal" },
            { id: "10244120", name: "絢爛なる鳳凰ほーちゃん", cost: 8, rarity: "レジェンド", group: "normal" },
            { id: "10244110", name: "銀氷の竜少女フィルレイン", cost: 2, rarity: "レジェンド", group: "normal" },
            { id: "10144130", name: "龍人演義ガリュウ", cost: 8, rarity: "レジェンド", group: "normal" },
        ]
    },
    "ナイトメア": {
        classCards: [
            { id: "10352110", name: "混融の祈祷者", cost: 4, rarity: "シルバー", group: "new" },
            { id: "10351120", name: "泡沫の鬼姫", cost: 8, rarity: "ブロンズ", group: "new" },
            { id: "10351310", name: "暴虐の行進", cost: 4, rarity: "ブロンズ", group: "new" },
            { id: "10351110", name: "混融の肯定者", cost: 3, rarity: "ブロンズ", group: "new" },
            { id: "10353110", name: "混融の団結者", cost: 5, rarity: "ゴールド", group: "new" },
            { id: "10352120", name: "フレッシュグレイブキーパー", cost: 2, rarity: "シルバー", group: "new" },
            { id: "10352210", name: "混融の城", cost: 2, rarity: "シルバー", group: "new" },
            { id: "10353310", name: "叫喚と憎悪", cost: 3, rarity: "ゴールド", group: "new" },
            { id: "10354120", name: "絶叫と愛絶の顕現ルルナイ&ヴァーナレク", cost: 7, rarity: "レジェンド", group: "new" },
            { id: "10354110", name: "混融の継承者シャム=ナクア", cost: 2, rarity: "レジェンド", group: "new" },

            { id: "10051130", name: "悪辣のレッサーマミー", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10051310", name: "カオティックカース", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10051120", name: "夜の鬼人", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10051110", name: "ウルフマスター", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10151310", name: "死神の一振り", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10151120", name: "無名の悪魔", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10151130", name: "ボーンガール", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10151110", name: "ミッドナイトヴァンパイアエラル", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10151150", name: "禁約の悪魔", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10151140", name: "ジャグリングゴースト", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10251310", name: "カースパーティー", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10251110", name: "シルバーバレットレイヴン", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10251120", name: "怨恨の栽培者", cost: 1, rarity: "ブロンズ", group: "normal" },

            { id: "10052110", name: "魅惑のサキュバスリリム", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10052310", name: "魂の捕食", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10052120", name: "ラバーズネクロマンサー", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10152120", name: "ナイトメアヴェリィ", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10152110", name: "辣腕の死神ミーノ", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10152210", name: "瞑地の霊園", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10152130", name: "怪奇の探索者ユナ", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10152140", name: "串刺し公ヴラド", cost: 8, rarity: "シルバー", group: "normal" },
            { id: "10252310", name: "蝙蝠の使役", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10252110", name: "ブラストウィングピユラ", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10252120", name: "コープスソルジャー", cost: 6, rarity: "シルバー", group: "normal" },

            { id: "10153310", name: "蛇神の怒り", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10153120", name: "燃え盛る魔剣オルトロス", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10153140", name: "闇の賞金稼ぎバルト", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10153110", name: "青薔薇の令嬢セレス", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10153130", name: "瞑地の天宮ムカン", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10253120", name: "ノクターンジェネラルエクセラ", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10253110", name: "クルーエルウォーラウラ", cost: 3, rarity: "ゴールド", group: "normal" },

            { id: "10154130", name: "エンドレスハンターアラガヴィ", cost: 5, rarity: "レジェンド", group: "normal" },
            { id: "10154120", name: "猛毒姫メドゥーサ", cost: 7, rarity: "レジェンド", group: "normal" },
            { id: "10154110", name: "奔放なる獄炎ケルベロス", cost: 8, rarity: "レジェンド", group: "normal" },
            { id: "10254120", name: "流れ堕つ冥河カローン", cost: 5, rarity: "レジェンド", group: "normal" },
            { id: "10254110", name: "双輪夜行ギンセツ&ユヅキ", cost: 09, rarity: "レジェンド", group: "normal" },
        ]
    },
    "ビショップ": {
        classCards: [
            { id: "10362210", name: "安息の神殿", cost: 3, rarity: "シルバー", group: "new" },
            { id: "10361110", name: "安息の肯定者", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10361120", name: "聖騎士の団員", cost: 2, rarity: "ブロンズ", group: "new" },
            { id: "10361310", name: "セイントフラッシュ", cost: 4, rarity: "ブロンズ", group: "new" },
            { id: "10363210", name: "輝く失意", cost: 4, rarity: "ゴールド", group: "new" },
            { id: "10362220", name: "有翼の獅子像", cost: 3, rarity: "シルバー", group: "new" },
            { id: "10362110", name: "安息の祈祷者", cost: 3, rarity: "シルバー", group: "new" },
            { id: "10363110", name: "安息の団結者", cost: 5, rarity: "ゴールド", group: "new" },
            { id: "10364110", name: "安息の継承者ヒメカ", cost: 6, rarity: "レジェンド", group: "new" },
            { id: "10364120", name: "絶望の顕現マーウィン", cost: 4, rarity: "レジェンド", group: "new" },

            { id: "10061120", name: "清純なる白狐", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10061130", name: "ウィングウォーリアー", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10061210", name: "投影の鳥像", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10061110", name: "癒しのシスター", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10161210", name: "穏やかなる教会", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10161140", name: "潜みしマイニュ", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10161110", name: "聖心のプリズムプリースト", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10161120", name: "セイントシールダー", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10161130", name: "標を与えるレディアンスエンジェル", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10161310", name: "フェザーレイン", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10261210", name: "光の香炉", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10261110", name: "粉砕の聖職者", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10261120", name: "マリスオラクルダムス", cost: 2, rarity: "ブロンズ", group: "normal" },

            { id: "10062210", name: "有翼の石像", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10062110", name: "鉄拳の神父", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10062120", name: "セイクリッドグリフォン", cost: 8, rarity: "シルバー", group: "normal" },
            { id: "10162210", name: "禁密の聖地", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10162110", name: "煌槍のアルミラージサリッサ", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10162220", name: "セイクリッドインジェクション", cost: 3, rarity: "シルバー", group: "normal" },
            { id: "10162120", name: "煌翼のフェザーフォルクリノ", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10162130", name: "大地の守護神ミーヴェ", cost: 7, rarity: "シルバー", group: "normal" },
            { id: "10262120", name: "潔癖の審判者", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10262310", name: "ディバインガード", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10262110", name: "バラージエクソシストコレット", cost: 3, rarity: "シルバー", group: "normal" },

            { id: "10163210", name: "獣姫の誓約", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10163120", name: "禁密の天宮ロナヴェロ", cost: 4, rarity: "ゴールド", group: "normal" },
            { id: "10163110", name: "終焉のスカルフェイン", cost: 6, rarity: "ゴールド", group: "normal" },
            { id: "10163220", name: "邪教の器", cost: 6, rarity: "ゴールド", group: "normal" },
            { id: "10163130", name: "大いなる熾天使ラピス", cost: 8, rarity: "ゴールド", group: "normal" },
            { id: "10263310", name: "狂おしき恩寵", cost: 2, rarity: "ゴールド", group: "normal" },
            { id: "10263110", name: "速断の刃アニエス", cost: 5, rarity: "ゴールド", group: "normal" },

            { id: "10164130", name: "水の守護神サレファ", cost: 5, rarity: "レジェンド", group: "normal" },
            { id: "10164110", name: "裁決のアナテマロデオ", cost: 7, rarity: "レジェンド", group: "normal" },
            { id: "10164120", name: "純白の聖女ジャンヌ", cost: 8, rarity: "レジェンド", group: "normal" },
            { id: "10264110", name: "天の守護神アイテール", cost: 7, rarity: "レジェンド", group: "normal" },
            { id: "10264120", name: "嗚咽の聖騎士ウィルバート", cost: 6, rarity: "レジェンド", group: "normal" },
        ]
    },
    "ネメシス": {
        classCards: [
            { id: "10372120", name: "フィールドエンジニア", cost: 5, rarity: "シルバー", group: "new" },
            { id: "10371120", name: "音速の飛行兵", cost: 7, rarity: "ブロンズ", group: "new" },
            { id: "10371110", name: "破壊の肯定者", cost: 4, rarity: "ブロンズ", group: "new" },
            { id: "10371310", name: "ストリングアサルト", cost: 4, rarity: "ブロンズ", group: "new" },
            { id: "10373310", name: "殲滅の歌声", cost: 2, rarity: "ゴールド", group: "new" },
            { id: "10372210", name: "破壊の荒野", cost: 2, rarity: "シルバー", group: "new" },
            { id: "10372110", name: "破壊の祈祷者", cost: 2, rarity: "シルバー", group: "new" },
            { id: "10373110", name: "破壊の団結者", cost: 6, rarity: "ゴールド", group: "new" },
            { id: "10374110", name: "破壊の継承者アクシア", cost: 3, rarity: "レジェンド", group: "new" },
            { id: "10374120", name: "奏絶の顕現リーシェナ", cost: 4, rarity: "レジェンド", group: "new" },

            { id: "10171320", name: "アーティファクトチャージ", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10171110", name: "ビビッドインベンターイリス", cost: 1, rarity: "ブロンズ", group: "normal" },
            { id: "10171130", name: "アンストッパブルガンナー", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10071120", name: "マリオネットランサー", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10171140", name: "オートマタアサシン", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10171310", name: "人形の身代わり", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10071110", name: "砲撃の猫獣人", cost: 3, rarity: "ブロンズ", group: "normal" },
            { id: "10071310", name: "異次元からの銃撃", cost: 4, rarity: "ブロンズ", group: "normal" },
            { id: "10171120", name: "メタルマーセナリーディルク", cost: 5, rarity: "ブロンズ", group: "normal" },
            { id: "10071130", name: "獣性の鉄人", cost: 6, rarity: "ブロンズ", group: "normal" },
            { id: "10271210", name: "アーティファクトカタパルト", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10271120", name: "パペットキャット", cost: 2, rarity: "ブロンズ", group: "normal" },
            { id: "10271110", name: "エンジンブレイダー", cost: 6, rarity: "ブロンズ", group: "normal" },

            { id: "10172120", name: "愛執のドールユーザー", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10172310", name: "命の奔流", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10072110", name: "エレクトロウィッパー", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10072210", name: "ドールズシアター", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10172110", name: "ストラグルリーダールキナ", cost: 4, rarity: "シルバー", group: "normal" },
            { id: "10172320", name: "改境の再動", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10072120", name: "魔鋼の騎兵", cost: 5, rarity: "シルバー", group: "normal" },
            { id: "10172130", name: "殺意の糸ノア", cost: 6, rarity: "シルバー", group: "normal" },
            { id: "10272310", name: "イカロスの飛翔", cost: 1, rarity: "シルバー", group: "normal" },
            { id: "10272110", name: "ハートスローターフィア", cost: 2, rarity: "シルバー", group: "normal" },
            { id: "10272120", name: "ディスペアロードアキム", cost: 5, rarity: "シルバー", group: "normal" },

            { id: "10173110", name: "レゾリューションミリアム", cost: 3, rarity: "ゴールド", group: "normal" },
            { id: "10173210", name: "遺産の砲撃", cost: 5, rarity: "ゴールド", group: "normal" },
            { id: "10173140", name: "改境の天宮アルエット", cost: 5, rarity: "ゴールド", group: "normal" },
            { id: "10173120", name: "箱庭の断罪者シルヴィア", cost: 6, rarity: "ゴールド", group: "normal" },
            { id: "10173130", name: "狂気の創造者リーアム", cost: 10, rarity: "ゴールド", group: "normal" },
            { id: "10273310", name: "心有る共闘", cost: 6, rarity: "ゴールド", group: "normal" },
            { id: "10273110", name: "暗獄の残光ジャスパー", cost: 2, rarity: "ゴールド", group: "normal" },

            { id: "10174110", name: "新たなる少女エース", cost: 3, rarity: "レジェンド", group: "normal" },
            { id: "10174130", name: "ブーストエクステンドララミア", cost: 8, rarity: "レジェンド", group: "normal" },
            { id: "10174120", name: "プロシードハートオーキス", cost: 8, rarity: "レジェンド", group: "normal" },
            { id: "10274120", name: "マインドアーツカルラ", cost: 6, rarity: "レジェンド", group: "normal" },
            { id: "10274110", name: "シンフォニアハートツヴァイ", cost: 5, rarity: "レジェンド", group: "normal" },
        ]
    },

};
